// arithmetic utils
export { default as setDefaultDecimalDigits } from './setDefaultDecimalDigits'
export { default as roundNumber } from './roundNumber'
export { default as getNumberInBetween } from './getNumberInBetween'
export { default as clamp } from './clamp'
export { default as linerarInterpolation } from './linerarInterpolation'
export { default as lerp } from './lerp'
export { default as getRandomNumber } from './getRandomNumber'
export { default as getPercentageOfValue } from './getPercentageOfValue'
export { default as getValueOfPercentage } from './getValueOfPercentage'
export { default as getLogarithmicValueOfPercentage } from './getLogarithmicValueOfPercentage'
export { default as getLogarithmicPercentageOfValue } from './getLogarithmicPercentageOfValue'
export { default as getAverage } from './getAverage'
export { default as getGreatCommonDivisor } from './getGreatCommonDivisor'
export { default as valuesAreSimilar } from './valuesAreSimilar'
export { default as factorial } from './factorial'
export { default as naturalNumbersSummation } from './naturalNumbersSummation'
