// arithmetic utils
export { default as setDefaultDecimalDigits }  from './mathUtils/setDefaultDecimalDigits'
export { default as roundNumber }  from './mathUtils/roundNumber'
export { default as getNumberInBetween }  from './mathUtils/getNumberInBetween'
export { default as clamp }  from './mathUtils/clamp'
export { default as linerarInterpolation }  from './mathUtils/linerarInterpolation'
export { default as lerp }  from './mathUtils/lerp'
export { default as getRandomNumber }  from './mathUtils/getRandomNumber'
export { default as getPercentageOfValue }  from './mathUtils/getPercentageOfValue'
export { default as getValueOfPercentage }  from './mathUtils/getValueOfPercentage'
export { default as getLogarithmicValueOfPercentage }  from './mathUtils/getLogarithmicValueOfPercentage'
export { default as getLogarithmicPercentageOfValue }  from './mathUtils/getLogarithmicPercentageOfValue'
export { default as getAverage }  from './mathUtils/getAverage'
export { default as getGreatCommonDivisor }  from './mathUtils/getGreatCommonDivisor'
export { default as valuesAreSimilar }  from './mathUtils/valuesAreSimilar'
export { default as factorial }  from './mathUtils/factorial'
export { default as naturalNumbersSummation }  from './mathUtils/naturalNumbersSummation'
