// arithmetic utils
export { setDefaultDecimalDigits }  from './mathUtils/setDefaultDecimalDigits'
export { roundNumber }  from './mathUtils/roundNumber'
export { getNumberInBetween }  from './mathUtils/getNumberInBetween'
export { clamp }  from './mathUtils/clamp'
export { linerarInterpolation }  from './mathUtils/linerarInterpolation'
export { lerp }  from './mathUtils/lerp'
export { getRandomNumber }  from './mathUtils/getRandomNumber'
export { getPercentageOfValue }  from './mathUtils/getPercentageOfValue'
export { getValueOfPercentage }  from './mathUtils/getValueOfPercentage'
export { getLogarithmicValueOfPercentage }  from './mathUtils/getLogarithmicValueOfPercentage'
export { getLogarithmicPercentageOfValue }  from './mathUtils/getLogarithmicPercentageOfValue'
export { getAverage }  from './mathUtils/getAverage'
export { getGreatCommonDivisor }  from './mathUtils/getGreatCommonDivisor'
export { valuesAreSimilar }  from './mathUtils/valuesAreSimilar'
export { factorial }  from './mathUtils/factorial'
export { naturalNumbersSummation }  from './mathUtils/naturalNumbersSummation'
